---
title: "Neuronal analysis"
author: "Spyros"
date: "10/5/2017"
output: html_document
---

```{r Set root directory and tissue of interest}
rootdir = "/Volumes/GoogleDrive/My Drive/MACA_Spyros/3M_data/Seurat_analysis/"
```

```{r  Subset Seurat oject}
rm("tiss.sub")
suffix <- "Neurons"
cluster <- "neurons"
cells <- c()
for(i in 1:length(cluster)){
  a <- row.names(tiss@meta.data)[which(tiss@meta.data$annotation==cluster[i])]
  cells <- c(cells,a)
}
tiss.sub <- SubsetData(object = tiss,cells.use = cells)
```


```{r Classify neurons based on expression of GAD1 and SLC17a7}
temp <- cbind(tiss.sub@data["Gad1",],tiss.sub@data["Slc17a7",])

# Convert to binary 
temp[which(temp > 0)] <- 1
# 
tiss.sub@meta.data[,"Neuron.subtype"]  <- NA
for(i in 1:nrow(tiss.sub@meta.data)){
  cell <- row.names(tiss.sub@meta.data)[i]
  if(temp[cell,][1]==1 & temp[cell,][2]==0) {tiss.sub@meta.data[i,"Neuron.subtype"] <- "inhibitory"}
  if(temp[cell,][1]==0 & temp[cell,][2]==1) {tiss.sub@meta.data[i,"Neuron.subtype"] <- "excitatory"}
  if(temp[cell,][1]==0 & temp[cell,][2]==0) {tiss.sub@meta.data[i,"Neuron.subtype"] <- "undetermined"}
  if(temp[cell,][1]==1 & temp[cell,][2]==1) {tiss.sub@meta.data[i,"Neuron.subtype"] <- "doublet"}
}
table(tiss.sub@meta.data[,"Neuron.subtype"])
table(tiss.sub@meta.data[,"Neuron.subtype"],as.character(tiss.sub@meta.data[,"subtissue"]))
# Write back to initial Seurat object 
tiss@meta.data[,"Neuron.subtypes"] <- NA
for(i in 1:nrow(tiss.sub@meta.data)){
  a <- which(row.names(tiss@meta.data)==row.names(tiss.sub@meta.data)[i])
  tiss@meta.data[a,"Neuron.subtypes"] <- tiss.sub@meta.data[i,"Neuron.subtype"]
  tiss@meta.data[a,"subannotation"] <- tiss.sub@meta.data[i,"Neuron.subtype"]
}
tiss@meta.data
table(tiss@meta.data$annotation, tiss@meta.data$subannotation)
```
```{r MArker analysis between excitatory and inhibitory neurons}
tiss.sub@meta.data[,"type.subtissue"] <- paste(tiss.sub@meta.data$Neuron.subtype,tiss.sub@meta.data$subtissue,sep="." )
#unique(tiss.sub@meta.data$type.subtissue)
cells.1 <- row.names(tiss.sub@meta.data)[which(tiss.sub@meta.data$type.subtissue=="excitatory.Cortex")]
cells.2 <- row.names(tiss.sub@meta.data)[which(tiss.sub@meta.data$type.subtissue=="excitatory.Cerebellum")]
# Clalculate AUC values
# Inhibitory
temp.inh <- MarkerTest(object = tiss.sub, cells.1 = cells.1, cells.2 = cells.2)
title <- paste("/Volumes/GoogleDrive/My Drive/MACA_Spyros/3M_data/Seurat_analysis/brain/",suffix,"/excitatory_AUC_CTX_to_excitatory_CB.csv", sep="")
write.table(temp.inh,file=title)
# Excitatory
temp.exc <- MarkerTest(object = tiss.sub, cells.1 = cells.2, cells.2 = cells.1)
title <- paste("/Volumes/GoogleDrive/My Drive/MACA_Spyros/3M_data/Seurat_analysis/brain/",suffix,"/excitatory_AUC_CB_to_excitatory_CTX.csv", sep="")
write.table(temp.exc,file=title)
save.image(file = "Brain_3M_latest.RData")
tiss.sub.neurons <- tiss.sub

# Save object 
subtiss.name = 'neurons_brain'
save(tiss.sub, file=paste0(save_dir,"/",subtiss.name, "_seurat_subtiss.Robj"))

```



