Figure 1.
```{r}
filename = make_filename(save_folder, 'allcells', 'cell_ontology_class', 'ridgeplot_scaled_Ppy')
RidgePlot(tiss, c('Ppy'), group.by = "cell_ontology_class")
ggsave(filename, dpi=300)
dev.off()
write_caption("The transcript of PP cell signature hormone, \\emph{Ppy}, is detected in delta cells at high levels.", filename)
```

Figure 2.
```{r}
prefix = 'DeltaCells'

#Subset delta cells for analysis
anno = 'pancreatic D cell'
cells.to.use = tiss@cell.names[which(tiss@meta.data$cell_ontology_class == anno)]
delta <- SubsetData(object = tiss, cells.use = cells.to.use, do.center = F, do.scale = F)

#2a - using scaled data.

filename = make_filename(save_folder, 'allcells', 'cell_ontology_class', 'ridgeplot_scaled_Neurog3')
RidgePlot(tiss,'Neurog3', group.by = "cell_ontology_class")
ggsave(filename, dpi=300)
dev.off()
write_caption("\\emph{Neurog3} transcripts are detected in islet, a few alpha, beta, and the majority of delta cells.", filename)

delta.1=FetchData(delta, c("ident", "mouse.id","cell_ontology_class", "mouse.sex", "plate.barcode", "subtissue", "percent.ercc", "percent.ribo","nGene", "nReads","Sst","Pdx1","Hhex","Neurog3", "Ins2", "Gcg", "Ppy","Actb","Gapdh"))
delta.1$mouse.id <- as.factor(delta.1$mouse.id)

filename = file.path(save_folder, paste(prefix, 'Neurog3_expression', 'scatterplot_scaled_Neurog3-x-Hhex'))
filename = make_filename(save_folder, prefix, 'Neurog3>0', 'scatterplot_scaled_Neurog3-x-Hhex')
ggplot(delta.1, aes(Hhex, Neurog3, color = Neurog3 > 0))+ geom_point() + geom_rug(sides="bl")
ggsave(filename, dpi=300)
dev.off()
write_caption("Scatter plot of all delta cells reveals that \\emph{Neurog3} and \\emph{Hhex} mark three distinct groups of
delta cells, i.e. \\emph{Neurog3}$^+$\\emph{Hhex}$^\\text{neg}$, \\emph{Neurog3}$^\\text{neg}$\\emph{Hhex}$^+$, and \\emph{Neurog3}$^+$\\emph{Hhex}$^+$.", filename)

filename = make_filename(save_folder, prefix, 'mouse.id', 'scatterplot_scaled_Neurog3-x-Hhex')
ggplot(delta.1, aes(x=Hhex, y=Neurog3, color = mouse.id)) + geom_point() + geom_rug(sides = "bl")
ggsave(filename, dpi=300)
dev.off()
write_caption("Delta heterogeneity is observed in every individual mouse.", filename)

#2b - using raw data.
filename = make_filename(save_folder, 'allcells', 'cell_ontology_class', 'ridgeplot_raw_Neurog3')
RidgePlot(tiss,'Neurog3', group.by = "cell_ontology_class", use.raw = TRUE)
ggsave(filename, dpi=300)
dev.off()
write_caption("\\emph{Neurog3} transcripts are detected in islet, a few alpha, beta, and the majority of delta cells.", filename)

delta.2=FetchData(delta, c("ident", "mouse.id","cell_ontology_class", "mouse.sex", "plate.barcode", "subtissue", "percent.ercc", "percent.ribo", "nGene", "nReads", "Sst", "Pdx1", "Hhex", "Neurog3", "Ins2", "Gcg", "Ppy", "Actb", "Gapdh"), use.raw = TRUE)
delta.2$mouse.id <- as.factor(delta.2$mouse.id)

filename = make_filename(save_folder, prefix, 'Neurog3>0', 'scatterplot_raw_Neurog3-x-Hhex')
ggplot(delta.2, aes(Hhex, Neurog3, color = Neurog3 > 0))+ geom_point() + geom_rug(sides="bl")
ggsave(filename, dpi=300)
dev.off()
write_caption("Scatter plot of all delta cells reveals that \\emph{Neurog3} and \\emph{Hhex} mark three distinct groups of
delta cells, i.e. \\emph{Neurog3}$^+$\\emph{Hhex}$^\\text{neg}$, \\emph{Neurog3}$$^\\text{neg}$$\\emph{Hhex}$^+$, and \\emph{Neurog3}$^+$\\emph{Hhex}$^+$.", filename)

filename = make_filename(save_folder, prefix, 'mouse.id', 'scatterplot_raw_Neurog3-x-Hhex')
ggplot(delta.2, aes(x=Hhex, y=Neurog3, color = mouse.id)) + geom_point() + geom_rug(sides = "bl")
ggsave(filename, dpi=300)
dev.off()
write_caption("Delta heterogeneity is observed in every individual mouse.", filename)
```

Figure 3.
```{r}
filename = make_filename(save_folder, prefix, 'expression', 'tsneplot')
FeaturePlot(tiss, c('Prss53', 'Slc2a2', 'Nkx6-1','Ins2'), cols.use = c("grey","blue"))
ggsave(filename, dpi=300)
dev.off()
write_caption("\\emph{Prss53} transcripts are only detected in islet beta cells.", filename)
```
