---
title: "Global Figures"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(Seurat)
library(viridis)
```

# Global TSNE

```{r, fig.width = 8, fig.height = 6}
FetchData(tiss, vars.all = c('tSNE_1','tSNE_2', 'color')) %>% 
  ggplot(aes(x = tSNE_1, y = tSNE_2)) + geom_point(aes(color = color), size=0.1) +
   scale_color_identity(breaks = tissue_colors$color, 
                        labels = tissue_colors$anno_tissue, 
                        guide = "legend") + 
  guides(colour = guide_legend(override.aes = list(size=2)))

#ggsave('figures/tsne_by_tissue_plates.pdf', width = 14, height = 7, units = "in")
```

```{r, fig.width = 8, fid.height = 6}
FetchData(tissX, vars.all = c('tSNE_1','tSNE_2', 'color')) %>% 
  ggplot(aes(x = tSNE_1, y = tSNE_2)) + geom_point(aes(color = color), size=0.1) +
   scale_color_identity(breaks = tissue_colors$color, 
                        labels = tissue_colors$anno_tissue, 
                        guide = "legend") + 
  guides(colour = guide_legend(override.aes = list(size=2)))

ggsave('figures/tsne_by_tissue_tenx.pdf', width = 14, height = 7, units = "in")
```

# Heatmaps for big clustering

```{r}
hmap_df <- FetchData(tiss, vars.all = c('cell_ontology_class','anno_tissue', 'cluster')) %>% 
  drop_na(cell_ontology_class) %>% 
  mutate(anno_and_tissue = paste0(cell_ontology_class, " (", anno_tissue, ")")) %>% 
  drop_na(anno_and_tissue) %>% 
  group_by(anno_and_tissue, cluster) %>% 
  summarize(count = n()) %>% filter(count > 5) %>% 
  spread(key=cluster, value = count, fill = 0)
```

```{r}
#save(hmap_df, file = 'save/hmap_df.Robj')
```


Do we see mixing of tissues and cell types in the top-level clustering?


```{r, fig.width = 15, fig.height = 45}
hmap_mat <- as.data.frame(hmap_df %>% ungroup() %>% select(-anno_and_tissue))
row.names(hmap_mat) <- hmap_df$anno_and_tissue

gplots::heatmap.2(as.matrix(log10(hmap_mat+1)), col = viridis(100), trace = "none", margins=c(10,36), Colv=TRUE, dendrogram = "row", cexRow = 2.0, cexCol = 2.0, key = FALSE, keysize = 0.05, distfun=function(x) as.dist(1-cor(t(x))))
```

