---
title: "Figure 3"
output: html_document
---

Heatmap with dendrogram for cluster vs annotation of all FACS cells.

```{r}
library(tidyverse)
library(stringr)
library(here)
library(Seurat)
library(viridis)
library(RColorBrewer)
```

## FACS

```{r}
load(file=here("00_data_ingest", "11_global_robj", "FACS_all.Robj"))
```

```{r}
hmap_df <- FetchData(tiss_FACS, vars.all = c('cell_ontology_class','tissue', 'cluster')) %>% 
  drop_na(cell_ontology_class) %>% 
  mutate(anno_and_tissue = paste0(cell_ontology_class, " (", str_replace(tissue, "_", " "), ")")) %>% 
  drop_na(anno_and_tissue) %>% 
  group_by(anno_and_tissue, cluster) %>% 
  summarize(count = n()) %>% filter(count > 5) %>% 
  spread(key=cluster, value = count, fill = 0)
```


```{r, fig.width = 25, fig.height = 45}
rnames = hmap_df$anno_and_tissue
hmap_mat <- as.data.frame(hmap_df %>% ungroup() %>% select(-anno_and_tissue))
row.names(hmap_mat) <- rnames

pdf(here("03_figure3","heatmap_facs.pdf"), width = 25, height = 45)

gplots::heatmap.2(as.matrix(log10(hmap_mat+1)), col = colorRampPalette(c("white","red"))(256), trace = "none", margins=c(10,50), Colv=TRUE, dendrogram = "n", cexRow = 2.0, cexCol = 2.0, key = FALSE, keysize = 0.05, distfun=function(x) as.dist(1-cor(t(x))))

dev.off()
```

For some reason the colorscale is not showing. We synthesize one:

```{r}
log_counts = hmap_df %>% ungroup() %>% select(-anno_and_tissue) %>% 
  gather(key = cluster, value = value) %>% transmute(logvalue = log10(value + 1))

p <- ggplot(log_counts, aes(x = logvalue, y = logvalue, color = logvalue)) + geom_point() + scale_colour_gradient(low = "white", high = "red") + labs(color = "Log10(nCells + 1)")
legend = get_legend(p)

ggdraw(legend)
ggsave(here("03_figure3","heatmap_facs_legend.pdf"))
```

## Droplet

```{r}
load(file=here("00_data_ingest", "11_global_robj", "droplet_all.Robj"))
```

```{r}
hmap_df <- FetchData(tiss_droplet, vars.all = c('cell_ontology_class','tissue', 'cluster')) %>%
  drop_na(cell_ontology_class) %>% 
  mutate(anno_and_tissue = paste0(cell_ontology_class, " (", str_replace(tissue, "_", " "), ")")) %>% 
  drop_na(anno_and_tissue) %>% 
  group_by(anno_and_tissue, cluster) %>% 
  summarize(count = n()) %>% filter(count > 5) %>% 
  spread(key=cluster, value = count, fill = 0)
```

```{r, fig.width = 25, fig.height = 30}
rnames = hmap_df$anno_and_tissue
hmap_mat <- as.data.frame(hmap_df %>% ungroup() %>% select(-anno_and_tissue))
row.names(hmap_mat) <- rnames

pdf(here("03_figure3","heatmap_droplet.pdf"), width = 25, height = 30)

gplots::heatmap.2(as.matrix(log10(hmap_mat+1)), col = colorRampPalette(c("white","red"))(256), trace = "none", margins=c(10,50), Colv=TRUE, dendrogram = "n", cexRow = 2.0, cexCol = 2.0, key = FALSE, keysize = 0.05, distfun=function(x) as.dist(1-cor(t(x))))

dev.off()
```

```{r}
log_counts = hmap_df %>% ungroup() %>% select(-anno_and_tissue) %>% 
  gather(key = cluster, value = value) %>% transmute(logvalue = log10(value + 1))

p <- ggplot(log_counts, aes(x = logvalue, y = logvalue, color = logvalue)) + geom_point() + scale_colour_gradient(low = "white", high = "red") + labs(color = "Log10(nCells + 1)")
legend = get_legend(p)

ggdraw(legend)
ggsave(here("03_figure3","heatmap_droplet_legend.pdf"))
```