---
title: "Aorta facs Supplementary Notebook"
output: html_notebook
---

# Load data and make TSNEPlots, DotPlots and Ridgeplots of data

```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Aorta', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Aorta'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("Acta2", "Adipor1", "Alas2", "Car3", "Cd14", "Cd34", "Cd3e", "Cd74", "Cdh5", "Col1a2", "Col6a3", "Dcn", "Epcam", "Fabp4", "Fap", "Gypa", "H2-Aa", "H2-Ab1", "Icam1", "Kit", "Krt5", "Krt8", "Laptm5", "Myh11", "Myocd", "Pdgfra", "Pecam1", "Ptprc", "S100a4", "Selplg", "Sox18", "Syk", "Tagln", "Tek", "Timp2", "Vcam1", "Vegfa", "Vim", "Vwf")
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
```
