---
title: "Diaphragm facs Supplementary Notebook"
output: html_notebook
---

# Load data and make TSNEPlots, DotPlots and Ridgeplots of data

```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Diaphragm', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Diaphragm'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("C1qa", "Calcr", "Cd19", "Cd34", "Cd3d", "Cd44", "Cd69", "Cd79a", "Cd79b", "Cxcr4", "Fcer1g", "Foxp3", "Itga7", "Itgam", "Itgb1", "Klrb1b", "Myf5", "Myod1", "Pax3", "Pax7", "Pdgfra", "Pecam1", "Ptprc", "Sdc4", "Vcam1", "Vpreb3")
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```
