---
title: "Heart facs Supplementary Notebook"
output: html_notebook
---

# Load data and make TSNEPlots, DotPlots and Ridgeplots of data

```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Heart', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Heart'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c("subtissue"))

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("C1qa", "Cav1", "Cdh5", "Dcn", "Ehd3", "Fabp4", "Gsn", "Hbb-b1", "Myh11", "Npr3", "Pecam1", "Tie1", "Tnni3")
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```

## Subset: SUBSETA

```{r}
SubsetA.cells.use = rownames(tiss@meta.data)[tiss@meta.data$cell_ontology_class == "smooth muscle cell"]
write(paste("Number of cells in SubsetA subset:", length(SubsetA.cells.use)), stderr())
SubsetA.n.pcs = 5
SubsetA.res.use = 1
SubsetA.perplexity = 25
SubsetA.genes_to_check = c("Cnn1", "Kcnj8", "Myh11", "Postn")
SubsetA.tiss = SubsetData(tiss, cells.use=SubsetA.cells.use, )
SubsetA.tiss <- SubsetA.tiss %>% ScaleData() %>% 
  FindVariableGenes(do.plot = TRUE, x.high.cutoff = Inf, y.cutoff = 0.5) %>%
  RunPCA(do.print = FALSE)
SubsetA.tiss <- SubsetA.tiss %>% FindClusters(reduction.type = "pca", dims.use = 1:SubsetA.n.pcs, 
    resolution = SubsetA.res.use, print.output = 0, save.SNN = TRUE) %>%
    RunTSNE(dims.use = 1:SubsetA.n.pcs, seed.use = 10, perplexity=SubsetA.perplexity)
# Highlight which cells are in this subset
    
palette = brewer.pal(3, "YlGnBu")
colors.use = c(palette[1], 'grey50')
tiss@meta.data[, "SubsetA"] = NA
tiss@meta.data[SubsetA.cells.use, "SubsetA"] = "SubsetA" 
filename = make_filename(save_folder, prefix="SubsetA", 'highlighted', 
    'tsneplot_allcells')
p = TSNEPlot(
  object = tiss,
  do.return = TRUE,
  group.by = "SubsetA",
  no.axes = TRUE,
  pt.size = 1,
  no.legend = TRUE,
  colors.use = colors.use
)
ggsave(filename, width = 4, height = 4)
dot_tsne_ridge(SubsetA.tiss, SubsetA.genes_to_check,
    save_folder, prefix = "SubsetA", group.bys, "facs")

```