---
title: "Large_Intestine facs Supplementary Notebook"
output: html_notebook
---

```{r}
library(useful)
library(Seurat)
library(dplyr)
library(Matrix)
library(ontologyIndex)
library(tidyverse)
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Large_Intestine', 'facs')

tissue_of_interest = 'Large_Intestine'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c("subtissue"))

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = sort(c("Lgr5", "Krt20", "Slc26a3", "Atoh1", "Spdef", "Dclk1", "Chga", "Chgb", "Mki67"))
dot_tsne_violin(tiss, genes_to_check, save_folder, prefix = 'allcells', group.bys)
```


```{r}
tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
```

