---
title: "Liver facs Supplementary Notebook"
output: html_notebook
---



Optimize pngs for smaller knitted html file sizes
```{r setup}
library(knitr)
knit_hooks$set(optipng = hook_optipng)
```

# Load data for Liver facs


```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Liver', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Liver'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("Alb", "Apoa1", "Ass1", "Cd19", "Cd68", "Cd74", "Cd79a", "Cd79b", "Cdh1", "Clec4f", "Cxcr6", "Cyp2e1", "Cyp2f2", "Emr1", "Glul", "Gstp1", "Gulo", "Gzma", "Hal", "Hamp", "Il2rb", "Irf7", "Kdr", "Nkg7", "Nrp1", "Oat", "Oit3", "Pck1", "Pecam1", "Serpina1c", "Ttr", "Ubb", "Zap70")
```

# Make TSNEPlots, DotPlots and Ridgeplots of data

```{r use-optipng, optipng=''}
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```
