---
title: "Lung facs Supplementary Notebook"
output: html_notebook
---



Optimize pngs for smaller knitted html file sizes
```{r setup}
library(knitr)
knit_hooks$set(optipng = hook_optipng)
```

# Load data for Lung facs


```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Lung', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Lung'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

# Make sure cluster ids are numeric
tiss@meta.data[, 'cluster.ids'] = as.numeric(tiss@meta.data[, 'cluster.ids'])

# Concatenate original cell ontology class to free annotation
cell_ontology_class = replace_na(tiss@meta.data$cell_ontology_class, "NA")
free_annotation = sapply(tiss@meta.data$free_annotation,
    function(x) { if (is.na(x)) {return('')} else return(paste(":", x))},
    USE.NAMES = FALSE)
tiss@meta.data[, "free_annotation"] = paste(cell_ontology_class,
    free_annotation, sep='')

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("Ager", "Calca", "Ccr2", "Cd11b", "Cd11c", "Cd14", "Cd19", "Cd200r3", "Cd24a", "Cd3e", "Cd68", "Cd79a", "Cd8a", "Col1a1", "Csf1r", "Cx3cr1", "Cxcr4", "Epcam", "Foxj1", "H2-Aa", "Itgam", "Itgax", "Klrb1c", "Krt5", "Ly6c2", "Ly6g", "Marco", "Mrc1", "Pdpn", "Pecam1", "Ptprc", "Resp18", "Scgb1a1", "Scgb3a2", "Sftpb", "Wnt3a")
```

# Make TSNEPlots, DotPlots and Ridgeplots of data

```{r use-optipng, optipng='-o7'}
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```
