---
title: "Mammary_Gland facs Supplementary Notebook"
output: html_notebook
---

# Load data and make TSNEPlots, DotPlots and Ridgeplots of data

```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Mammary_Gland', 'facs')
dir.create(save_folder, recursive=TRUE)
method = "facs"

tissue_of_interest = 'Mammary_Gland'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("Aldh1a3", "Ccl5", "Cd14", "Cd19", "Cd3e", "Cd3g", "Cd55", "Cd74", "Cd79a", "Cdh5", "Csf1r", "Elf5", "Esam", "Esr1", "Fn1", "Krt14", "Krt17", "Krt18", "Krt19", "Krt5", "Krt8", "Lgr5", "Ly6c1", "Nkg7", "Pecam1", "Pgr", "Prlr", "Ptprc", "Vim")
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```

## Subset: BASAL

```{r}
Basal.cells.use = rownames(tiss@meta.data)[tiss@meta.data$cell_ontology_class == "basal cell"]
write(paste("Number of cells in Basal subset:", length(Basal.cells.use)), stderr())
# Basal.n.pcs = 10
# Basal.res.use = 0.5
# Basal.perplexity = 30
# Basal.genes_to_check = c("Areg", "Cited1", "Csn3", "Fos", "Id1", "Id2", "Igfbp2", "Igfpb4", "Prlr", "Procr", "Vcam1")
# Basal.tiss = SubsetData(tiss, cells.use=Basal.cells.use, )
# Basal.tiss <- Basal.tiss %>% ScaleData() %>% 
#   FindVariableGenes(do.plot = TRUE, x.high.cutoff = Inf, y.cutoff = 0.5) %>%
#   RunPCA(do.print = FALSE)
# Basal.tiss <- Basal.tiss %>% FindClusters(reduction.type = "pca", dims.use = 1:Basal.n.pcs, 
#     resolution = Basal.res.use, print.output = 0, save.SNN = TRUE) %>%
#     RunTSNE(dims.use = 1:Basal.n.pcs, seed.use = 10, perplexity=Basal.perplexity)
# Highlight which cells are in this subset
    
palette = brewer.pal(3, "YlGnBu")
colors.use = c(palette[1], 'grey50')
tiss@meta.data[, "Basal"] = "Not in subset"
tiss@meta.data[Basal.cells.use, "Basal"] = "Basal" 
filename = make_filename(save_folder, prefix="Basal", 'highlighted', 
    'tsneplot_allcells')
p = TSNEPlot(
  object = tiss,
  do.return = TRUE,
  group.by = "Basal",
  no.axes = TRUE,
  pt.size = 1,
  no.legend = TRUE,
  colors.use = colors.use
)
ggsave(filename, width = 4, height = 4)

```