---
title: "Thymus droplet Supplementary Notebook"
output: html_notebook
---



Optimize pngs for smaller knitted html file sizes
```{r setup}
library(knitr)
knit_hooks$set(optipng = hook_optipng)
```

# Load data for Thymus droplet


```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Thymus', 'droplet')
dir.create(save_folder, recursive=TRUE)
method = "droplet"

tissue_of_interest = 'Thymus'
filename = paste0('droplet_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("C3", "Cd14", "Cd19", "Cd27", "Cd3d", "Cd3e", "Cd3g", "Cd4", "Cd44", "Cd69", "Cd86", "Cd8a", "Cd8b1", "Dntt", "Epcam", "Ets1", "H2-Aa", "H2-Ab1", "Igfbp7", "Il2ra", "Il2rb", "Itgax", "Krt5", "Krt8", "Mki67", "Pdgfrb", "Ptcra", "Ptprc", "Rag1", "Rag2", "Runx3", "Top2a", "Vim", "Zbtb7b")
```

# Make TSNEPlots, DotPlots and Ridgeplots of data

```{r use-optipng, optipng='-o7'}
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix,
    group.bys = group.bys, method = method)
```

## Output differentially expressed genes in clusters

```{r}
#tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
#filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
#write.csv(tiss.markers, filename)
```
