---
title: "Thymus facs Supplementary Notebook"
output: html_notebook
---

# Load data and make TSNEPlots, DotPlots and Ridgeplots of data

```{r}
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Thymus', 'facs')
dir.create(save_folder, recursive=TRUE)

tissue_of_interest = 'Thymus'
filename = paste0('facs_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = c("Cd3d", "Cd3e", "Cd3g", "Cd4", "Cd44", "Cd69", "Cd8a", "Cd8b1", "Dntt", "Epcam", "Ets1", "H2-Aa", "H2-Ab1", "Il2ra", "Krt5", "Krt8", "Ptprc", "Rag1", "Rag2", "Top2a", "Vim")
dot_tsne_ridge(tiss, genes_to_check, save_folder, prefix = prefix, group.bys)
```

## Output differentially expressed genes in clusters

```{r}
tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
```
