---
title: "Tongue droplet Supplementary Notebook"
output: html_notebook
---

```{r}
library(useful)
library(Seurat)
library(dplyr)
library(Matrix)
library(ontologyIndex)
library(tidyverse)
library(here)
source(here('30_tissue_supplement_figures', 'supplemental_figures.R'))
save_folder = here('30_tissue_supplement_figures', 'Tongue', 'droplet')
dir.create(save_folder, recursive=TRUE)

tissue_of_interest = 'Tongue'
filename = paste0('droplet_',tissue_of_interest, '_seurat_tiss.Robj')
load(here('00_data_ingest', '04_tissue_robj_generated', filename))

additional.group.bys = sort(c())

group.bys = c(standard.group.bys, additional.group.bys)

genes_to_check = sort(c("Top2a", "Cdc20", "Mki67", "Krt15", "Krt5", "Krt14", "Sbsn", "Krt10", "Krt4", "Krt13", "Krt36", "Krt84", "Hoxc13"))
dot_tsne_violin(tiss, genes_to_check, save_folder, prefix = prefix, group.bys)
```


```{r}
tiss.markers <- FindAllMarkers(object = tiss, only.pos = TRUE, min.pct = 0.25, thresh.use = 0.25)
filename = file.path(save_folder, paste(prefix, 'findallmarkers.csv', sep='_'))
```


## To identify taste receptor cells

#```{r}
VlnPlot(tiss, c('Krt8', 'Krt19', 'Tas1r1', 'Tas1r2', 'Tas1r3', 'P2rx7'))
```

```{r}
genes_to_check = c('Krt8', 'Krt19', 'Tas1r1', 'Tas1r2', 'Tas1r3', 'P2rx7')
filename = file.path(save_folder, paste(prefix, group.by, 'violinplot.pdf', sep='_'))
  p = ViolinPlot(tiss, genes_to_check, group.by = column, do.return=TRUE)
  ggsave(filename, width = 6, height = 3)
  dev.off()
  ```
